apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jules-api-key
  namespace: jules-remediator
spec:
  encryptedData:
    api-key: AgC5L+E9EW2GlxQQBAcLZW5I0D9sSSEUjAuKyto8YlE9Pp3vdrHHoO7yajn5w2wu12j2t8odWUgrTIbi4U0W5+S9OYxSntULN2jBReRWVao8zjlGhjpVUkAI4fxbAgqChRuaTeXMYiBAXap+g8+qz0qMuD4hynNlFW4WqDV8PWm4WcksJ0SRyD1vzy7MLmTDVTqnktR+8Due6JV6ylnMWMz3MxUdt2v1aH82JyWfBq4sys2O7JkTfuA42BoQGin4Xu2ZTYaiXMP8f8bBlNLRE3q8EaaC27GFXitWwmp0HBCUgOP85S9cSeSAB13BxESl+favf0fwqDaiG/cV6t61fRkKtxTcgilN2iRXxKE8geUUNhNilNno2qox6tjnlB4Q0/a6uVhLGQakDDbFTMSX9AgpPen0Ux4+76+I/vf4kmpmAxZhK7/FC44REoDoJLx+sm3jx1cD/JmGjuHa1jwM7EtlgaCA+tAtut6pNGFguur3terV9A1cY2pId612zxj4zYjmkWIyULtt9AFC1b6S/aQ8s3foWIsfTRH2sH9WhAzZ5Yhxrgqb3QbZ84Yaroh2crPF+N1/ayMVexP9UybzuzsMIQGPSlfUl0w3hYEQMyl6vyYsaWsLzApZZnqm6FHN8VNgdsqPAinHcKu2O5OgqMTI38EOuCdGAFDBVCQYSPFAQEUR1zv0kzVzgVHJhfVWuvA/GtZx/b4dHzHAxYg6JCTfbI/Ungr0akgOXv/puDrGQrtJxuYuLSSiqR2Ww4paTIm6gAs3ewg=
  template:
    metadata:
      name: jules-api-key
      namespace: jules-remediator
    type: Opaque
