---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-secrets
  namespace: jules-remediator
spec:
  encryptedData:
    GITHUB_TOKEN: AgAIJdX/l8yEA6ztWT3o9Jok+HL8Wa+nkRHTnw8zoLTLliH4UqFh8bfqTyG0zT/ALc0uQnRRtCRM5y0KcVaa6aqQXS76iX2qdmocADfTIoG+faAPe5lM2+IyWG/tenMN9J+dIFm3hxighNb1uAmS2XWqoKxRIPelaSz38uEXoG3wJxCGC+9cLZPAKR4OC1X731PlLYog6bcTj5j3o3nNe8MW7Tz3SyBj8slNqwGYj7qXVu0XpFWa0IKd5XgKz7VOaksEpoP1KL43NoCebfCGPY8PYLXq7QS1dqpInTHJeI/H8HOz7wmSI/vMXyp/YeC7ZTw5ZlLT9UNVWLC4c1rIoXx8UCt6+i6hB7DcDFD5/JUkHZ10qjg9XH9k9LAlzqEXdO1nnjj074LIaWa0HrJ9YWfZZyaFPJNp1unpHTU1OKGRiyyQpLDSIBOKGXSUWY90lr23fCPRkPSwUzooaBjZV56jTmJ2SXwALFV4veEljlXBCDcXLScBJF/e5JKlqWRgm3Xfe9vCjv0oor7ow58SDODt5NiNaakyJ9eT/zJErXJAO0CAV3xTgkUjTqBymcx5ll93JHCuOssGY3cQDXTn8h2AXcVnmmxmPyd1jwCzpRAYwFzL02Hl/WZU6cNwg5hCWgfwbbN3Bsj9ARNdgfujRC2xuFXsDIAzgzIdEvwRGEPKAnQHlNrssLVXsg4iPKhMkfifcOG1i50pjpp1Od1+GBk+m+xqYz6EX8PbMa6g1j3TTUd46BTtB3xr
    LITELLM_MASTER_KEY: AgCfH4woAQwduQA34fa+4giCosDBMAF5HZNfOWuK7vgb05BnjdDDqT73HXlgv4Bl5EoC4CUG+D58iWPfku8LUNUC5dOUJcYzhRCNjxHtDoz6IskP8UJbrFdTk+3dYcS7fMOm0iRbuOj3D1P74pALis7+ggLmz+cg/XTiiwzsRoiFdvnYY47XzXuF7I2ZA+yx0ie+YEDuiNwxbOpAO951qghIdzLlMGBxT04048N/192ZzcygJOLVag2jWxIMp5wv4yhavmRHmbRfl8sjFaVLtNRQ7WSpLmRe7/hVfI0eTcO4f+9AaBZVc6kgX7z9bGN9zpEgnGG/eO+zFg5pPG4YsM5whez5V/vLEsrI4uykvyNlR7/wktxPU3I1is/nG+fwxUHHRi0VphoZ25iMTHXdlynJz5KyhX8xLrNOF4T41o6JkYaHAggNljPZdHumfpXfAS4JCCBWPd72/whBU6p0shs6KKjj0s7EtWa9OuRR0p+yJ9q4crAFk3BasKEE6W8eki9FPmrgJWAaKWk56I5I7lANFQrLicGLtoONRgLJJhwLleAk+3EPNFldvsCvQz9fGTQCXxHn1JTEYBSgjGiiYyyvckAIZlh8mTZOzKGieHEuuZ7+ecxyK5XKW+tNuZ20IikSUmfqKebxmQODhaC8GSisFQ8Y36+LsCtVproUiuaSCA/zMAhXEY8/zcHEU8HQ7IqRp32A6NGN
  template:
    metadata:
      name: litellm-secrets
      namespace: jules-remediator
