apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-secrets
  namespace: jules-remediator
spec:
  encryptedData:
    LITELLM_MASTER_KEY: AgCcO9hNlFqA0W2eLoP4q1fF2pHkeA6JzlgKQB8hoT7zxFB6AVwv77c3ZyVtU/dwAnaJUIS2hK8v1aJ9nLVVOkVedf0oIJc8710fZ9hZfp++wn+uQVMoLIL7RHL4rgCVVof/9QcdRhNHVsJfkHj+aBT3Cy/qT3aW+f0voGx6bA+PjhIqnVFXI4N+r4c97ypu4oijp5tIwNPsvDzIMMwyC0m45KHrWdAgCNuYXglI4LHyvoQQjzPrwUgpNUpLsSO79twt7QNOmKMP4SQggTzHbfNuJJw9oyxxrQ3rCZfhZ/9uzZxsetVkIH9kP9k2Ufq9nBriGKrutgJ3zRmJj6K+yNijoLfs/OEw863hV7B8TiiOZuop0m8lRFMgEBd/euwFQaavkpTtIp9KTfU53Bpxi5CZIVOmnnhpQCvvdtminZ3Z9gsuK9YdWmuLlcHFiTIyfgPeM3xjasiPCwYrG0UO8b5SBkO6KGjZ/yoxIgdGe9IJGii2TImN2i8xypy/JO+ERmeDXDdiV0zC0H+ZncABGAr/fTBqF7i5Q1I0N2i95yiQlYouraFy2f0bU97CpLrEtDdsGzFO8Q5ZZ3zWKMy/X/pcPWylfVS34A7bysQyWHK3XDaun3UIVcZLcplgu1Z0DWX4SCeVQaSYcncGWc3/oRS3nQKHCL9kjfHUv7GUqb2zza0aO42EtISwFSX4usakeHt8StEoXflhrIdEBOSrs6fr4kmpmAxZhK7/FC44REoDoJLx+sm3jx1cD/JmGjuHa1jwM7EtlgaCA+tAtut6pNGFguur3terV9A1cY2pId612zxj4zYjmkWIyULtt9AFC1b6S/aQ8s3foWIsfTRH2sH9WhAzZ5Yhxrgqb3QbZ84Yaroh2crPF+N1/ayMVexP9UybzuzsMIQGPSlfUl0w3hYEQMyl6vyYsaWsLzApZZnqm6FHN8VNgdsqPAinHcKu2O5OgqMTI38EOuCdGAFDBVCQYSPFAQEUR1zv0kzVzgVHJhfVWuvA/GtZx/b4dHzHAxYg6JCTfbI/Ungr0akgOXv/puDrGQrtJxuYuLSSiqR2Ww4paTIm6gAs3ewg=
  template:
    metadata:
      name: litellm-secrets
      namespace: jules-remediator
    type: Opaque
